name: CI/CD actions destroy

env:
   tf_actions_working_dir : ./ec2/example

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN : ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_DEFAULT_REGION: us-east-2

    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3    

      - name: Terraform initializing 
        id: init
        run: terraform init
        # working-directory: ${{ env.tf_actions_working_dir }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approves
        # working-directory: ${{ env.tf_actions_working_dir }}

      - name: Terraform destroy 
        id: destroy
        run: terraform destroy -auto-approve
        # working-directory: ${{ env.tf_actions_working_dir }}
      

