name: CI/CD actions plan

env:
   tf_actions_working_dir : ./ec2/example

on:
  push:
    branches: [ "main" , "master" ]
  pull_request:
    branches: [ "main" , "master" ]
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN : ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_DEFAULT_REGION: us-east-2

    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3    
        
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        # working-directory: ${{ env.tf_actions_working_dir }}
        continue-on-error: true  

      - name: Terraform initializing 
        id: init
        run: terraform init
        # working-directory: ${{ env.tf_actions_working_dir }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        # working-directory: ${{ env.tf_actions_working_dir }}

      - name: Terraform plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
        # working-directory: ${{ env.tf_actions_working_dir }}
        continue-on-error: true
